memcached:
    build: memcached

nginx:
    build: nginx
    volumes:
      - "./nginx/sites/:/etc/nginx/conf.d"
      - "./nginx/certs/:/etc/nginx/certs"
      - "./nginx/logs/:/var/log/nginx"
      - "./nginx/www/:/var/www"
    links:
      - jetty

jetty:
    build: jetty
    links:
      - memcached
    ports:
      - "62911:62911"
