memcached:
    build: memcached
    ports:
      - "60002:11211"

nginx:
    build: nginx
    ports:
      - "60003:80"
    volumes:
      - "./nginx/sites/:/etc/nginx/conf.d"
      - "./nginx/certs/:/etc/nginx/certs"
      - "./nginx/logs/:/var/log/nginx"
      - "./nginx/www/:/var/www"
    links:
      - jetty

jetty:
    build: jetty
    ports:
      - "60004:5001"
    links:
      - memcached

