zk:
  image: zk
  environment:
    ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
    ZK_ID: 1

master:
  build: mesos
  dockerfile: Dockerfile-dev-master
  environment:
    MESOS_ZK: zk://zk:2181/mesos
    MESOS_QUORUM: 1
    MESOS_CLUSTER: docker-compose
    MESOS_WORK_DIR: /var/lib/mesos
  links:
    - zk

slave1:
  build: mesos
  dockerfile: Dockerfile-dev-slave
  privileged: true
  environment:
    MESOS_MASTER: zk://zk:2181/mesos
    MESOS_CONTAINERIZERS: docker,mesos
    MESOS_PORT: 5051
    MESOS_RESOURCES: ports(*):[11000-11999]
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - zk

# slave2:
#   image: mesosphere/mesos-slave:0.26.0-0.2.145.ubuntu1404
#   net: host
#   pid: host
#   environment:
#     MESOS_MASTER: zk://zk:2181/mesos
#     MESOS_CONTAINERIZERS: docker,mesos
#     MESOS_PORT: 5052
#     MESOS_RESOURCES: ports(*):[12000-12999]
#   volumes:
#     - /sys/fs/cgroup:/sys/fs/cgroup
#     - /usr/local/bin/docker:/usr/bin/docker
#     - /var/run/docker.sock:/var/run/docker.sock
#   links:
#     - zk

marathon:
  build: marathon
  dockerfile: Dockerfile-dev
  environment:
    MARATHON_MASTER: zk://zk:2181/mesos
    MARATHON_DECLINE_OFFER_DURATION: 3600000
  links:
    - zk

#chronos:
#  image: mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.24.1-0.2.35.ubuntu1404
#  command: /usr/bin/chronos run_jar --http_port 8888 --master zk://zk:2181/mesos --zk_hosts zk://zk:2181/mesos
#  links:
#    - zk
