
#dns:
#    build: dnsmasq
#    ports:
#      - "53:5353/udp"
#    volumes:
#      - "./dnsmasq/dnsmasq.hosts:/dnsmasq.hosts"

nexusdata:
    build: nexus
    entrypoint: /bin/bash
           
nexus:
    build: nexus
    volumes_from:
      - nexusdata
    ports:
      - "8081:8081"

registrydata:
    build: registry
    entrypoint: /bin/bash

registry:
    build: registry
    volumes_from:
      - registrydata
    ports:
      - "8082:5000"

registryfe:
    build: registryfe 
    links:
      - registry:path-to-your-registry-v2
    ports:
      # Serves the page via grunt
      - "9000:9000"
      # For live reload with grunt
      - "35729:35729"
    volumes:
      - ./registryfe:/source:rw
      - ./registryfe/develop/start-develop.sh:/root/start-develop.sh:ro
